export {default as Loader} from './Loader';
export {default as Navbar} from './Navbar';
export {default as Services} from './Services';
export {default as Transactions} from './Transactions';
export {default as Welcome} from './Welcome';
export {default as Footer} from './Footer';
export {default as Tutorial} from '../routes/Tutorial';
export {default as Tuts} from './Tuts';
export {default as Terminology} from './Terminology';
export {default as Work} from './Work';
export {default as MarketPlace} from './MarketPlace';
export {default as Market } from '../routes/Market';
export {default as Hero} from './Hero';
